language: python
python: '2.7'
install:
- virtualenv buildout --no-setuptools
- mkdir -p buildout-cache/downloads
- buildout/bin/python bootstrap.py -c travis.cfg
- bin/buildout -N -t 3 -c travis.cfg ${VERSIONS}
before_script:
- gem install --version 0.8.9 faraday
- gem install travis-artifacts
script:
- bin/sphinx-build docs/source docs/html
after_script:
- travis-artifacts upload --path parts/test
- travis-artifacts upload --path docs/html
env:
  global:
  - ARTIFACTS_S3_BUCKET=collective.usermanual
  - secure: hGLEHf2WtG+HxAP2K+v24NgGMBehf14sHJF23Nsqh9eW8MdkVGWvvDDihjp7s2gh9CrodN0d/GO+3phOZcSbQ9cIwMhyvO+34gs5htbwlXjiehMH76kfvTgmgbMCgpYfegzrC/u6GIndhBjpzcQo4RRL4jnWPcBiqgk3sLByAHQ=
  - secure: QUw0eGGvYmY7v66lF4BQ2kuJVF+dtcwbBs2uQ6PsBvWoeva0Zi6QitH0vNnfT7ncF4JRGHnZrmOJAApr4bUOJ+E7avTzcuq0EPwqunHg/CSPVcDeZMvPFLMfR6zJ+ZoXljf7XGeN8d7At+CSbIhxalwzFYC5eSEMQk0OnV8S0eI=
notifications:
  irc:
    channels:
    - irc.freenode.org#plone-testing
    template:
    - ! '%{repository}#%{build_number} (%{branch} | %{commit} | %{author}): %{message}'
    - ! 'Robot: http://collective.usermanual.s3-website-us-east-1.amazonaws.com/artifacts/%{build_number}/%{build_number}.1/robot_report.html'
    - ! 'Sphinx: http://collective.usermanual.s3-website-us-east-1.amazonaws.com/artifacts/%{build_number}/%{build_number}.1/'
